import type { Metadata } from "next";
import Providers from "./components/Providers/Providers";
import Header from "./components/TranslatorDashboard/Header";
import { VStack } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Translator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <VStack p="0" m="0" h="100vh">
            <Header />
            {children}
          </VStack>
        </Providers>
      </body>
    </html>
  );
}
